name: Global Energy Recovery

on:
  schedule:
    # נסה לשנות את זה ל-10 דקות (לפעמים 5 זה תדיר מדי ו-GitHub מעכב את זה יותר)
    - cron: '*/10 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main # ירוץ פעם אחת בכל פעם שאתה מעלה קוד

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Firebase Admin
        run: npm install firebase-admin

      - name: Run Energy Update Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node update-energy.js
